### ISSUE TITLE
Check age of players when added to roster

### ISSUE THREAD

**Issue by bastrapp** [ultical/ultical#2]
Check if a player (based on his birthday) is eligible to player in this year and this division...

Maybe difficult for indoor season spanning over two years (one winter)

**Comment by bastrapp** [comment]
Nice work. But we have to consider different Master ages for male and female athletes...

**Comment by bslbckr** [comment]
... you trapp'd me

**Comment by bastrapp** [comment]
Hehe... open... close... Wanted to write something about it before closing: All ages (including the women-masters-gab) are now hardcoded... maybe one day in the future we should reexamine that

**Comment by bslbckr** [comment]
I thougt of a somehow more complicated solution, but the current one definetly solves the issue.
