### ISSUE TITLE
Special characters mapping

### ISSUE THREAD

**Issue by bastrapp** [ultical/ultical#23]
Characters with accents are not mapped to their 'base' character in DFV Name search results:

example:
search query `andre` won't return `andré`

**Comment by bastrapp** [comment]
The committed fix is working but not optimal in terms of sql overhead. Suggestions welcome...

**Comment by bastrapp** [comment]
Closed for now - maybe @kaffeetrinkr can have a look

**Comment by bslbckr** [comment]
I think we should leave it like this for the moment. If we register a too heavy load on the db, we should find a workaround. What I could imagine is a kind of name-normalization that converts all names to most similar ASCII representation. This should be done in the backend, when the sync task with dfv-mv.de runs and in the frontend each time a search request is sent to the backend. Of course at the backend the normalized name has to be stored in a separate column in DFV_MV_NAME.
