### ISSUE TITLE
Multiple Rosters per Season

### ISSUE THREAD

**Issue by bastrapp** [ultical/ultical#24]
This thought came to us, when we realized that also "Landesverbände" could organize official tournaments but maybe have different roster-policies or simply: players play with a different team during a Landesverband-competition.

It would be also very useful to minimize the "Team 2"s in the database as a Roster tagged with a name (e.g. 'Team 2') could coexist within the same team name.

The latter is straight-forward:
- let team admins tag rosters
- ask which roster to use at team-registration

The first issue concerning official tournaments is more tricky, as there might be Landes-Tournaments that serve as qualifications for nationwide championchips - thus the roster should be the same.

I see two alternatives:

(1) We link TournamentEditions together requiring the same roster for all of them
Teams could then tag there rosters whatever they like (DFV Team 1 or NRW Team 2).

Pro: We don't need any additional roster-policy-logic
Con: Teams could get confused which roster is needed for which tournament (if they don't name it right)

(2) At creation a roster is assigned not only an (optional) tag (e.g. Team 2) but also an association or a championshipFormat (to be created). Roster to Edition/Event mapping would be automatic then, as the fitting roster would be chosen.

Pro: Automatic roster to edition mapping
Con: We need to create a new class (championshipFormat) with a lot of logic.

I support (1) and wait for you comments, especially @kaffeetrinkr

**Comment by bastrapp** [comment]
If you think this even further, you could allow teams to specify a Teamname with each roster, allowing for (a) a different name for 'Team 2' (e.g. FrankP a.k.a. FrankN 2) (b) a team of a different division with different name (e.g. Frankas (Women), FrankN (Open), ...)

But this would go one step to far I would think ;-)

**Comment by bastrapp** [comment]
And I have to correct myself: 

alternative (2) cannot feature an automatic roster fitting, as there might be several rosters of the same division and season but different tags.

alternative (1) is more complicated than I thought: tournamentFormats need to be linked and not one can be forgotten to ensure that a player can only be in one relevant roster at a time.

So I switch to prefer (2) - we have "scopes" that loosely can be mapped to associations but there are more scopes than that: inter-association-championships, national squads, fun tournaments...

**Comment by bastrapp** [comment]
I am working on this right now and it's looking good... but now I have a UX problem I would like your input on: If we introduce tags to rosters (e.g. for "Team 2") and they register for tournament A with Team 1 and tournament B with Team 2, who gehts the info-mails from the tournament organizers? Always all team admins? Or should the admin be able to choose which email adresses to notify (this would add a lot more complexity to the user interface... and of course a couple more tables)...

**Comment by bslbckr** [comment]
Hey Bas,

great that you are making progress on this topic! Concerning your question I would go for the simple and - if you think on holidays, illness whatever - more robust variant of sending all mails to all team admins.

**Comment by bastrapp** [comment]
This issue should be resolved with #32
