### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by nuest** [ultical/ultical#5]
Right now the project source code is available on GitHub, but without stating a clear license, the code as such is not properly published as open source.

Which license? http://choosealicense.com/

If the existing contributors would pick a license, then I'd be happy to create a PR with the following changes:
- [x] create NOTICE file and check if licenses are compatible...
  - [x] for server
  - [x] for client/web frontend
- [x] add license information to README
  - AGPL for the server
  - GPL v3 for the client
- [x] add `LICENSE` file in root of each subproject
- [x] add license to pom file
- [x] add configuration for automatic code header adding (and automatic `NOTICE` file generation)...
  - [x] for Java/server-side project

**Comment by bastrapp** [comment]
Good point... we will discuss this.

Thanks for your offer.

**Comment by bastrapp** [comment]
We decided on GPLv3. It seems to be the best pick for us. Since we are not a library the copyleft chain would only apply to variations of this software, which we would love to be open source...

**Comment by bslbckr** [comment]
So @nuest did we understand you correctly, that you are willing to do the necessary modifications? I would appreciate that :)

**Comment by nuest** [comment]
GPL sounds like a good fit. If you want to enforce copyleft, you could even consider AGPL (Affero GPL) for the server side.

I am on vacation now but would be happy to make the changes when I am back!

Am 23. Januar 2016 15:32:16 MEZ, schrieb Basil notifications@github.com:

> So @nuest did we understand you correctly, that you are willing to do
> the necessary modifications? I would appreciate that :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bastrapp/ultical/issues/5#issuecomment-174190218

## 

Daniel Nüst
Institute for Geoinformatics (ifgi),   University of Münster
Heisenbergstraße 2, 48149 Münster, Germany; +49 251 83 31962
http://ifgi.uni-muenster.de/~d_nues01

**Comment by bastrapp** [comment]
You are right, I think we should go with AGPL. Thank you. And enjoy your vacations...

**Comment by bslbckr** [comment]
I agree. Let's go with the AGPL for the server

**Comment by nuest** [comment]
I'm back :-). These changes will affect all files, so I'd rather do them when you won't make larger changes for a couple of days. Is such a window coming up any time soon?

**Comment by bslbckr** [comment]
hmm, I'm not quite sure whether we will find such a time-slot. I just created a new branch that will keep me busy for some time (make-dfv-stuff-optional). 
Of course, adding a license header will involve modifications for all files, but these modifications occur at a very specific location within the files. Should be save to go on, at least from my point of view. @bastrapp  what's your opinion on this topic?

**Comment by bastrapp** [comment]
I am with you @kaffeetrinkr ... I Think git will do a good job managing the merges

**Comment by ChristianUlbrich** [comment]
I don't think, that every file needs to have a licence. Is that really common in JavaLand? At least we need a licence.md in the root dir; that should do it for the beginning. If someone is really trying to rip us of, they won't be hindered by a licence in every file... Of course, when it is automated...

**Comment by nuest** [comment]
Yes, the is common:
- https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/ArrayUtils.java
- https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/BeanInfoFactory.java

Apache & Spring have it, I'm sure there are more.

I have a new suggestion to make progress with this: I'ld like to split the PR #18 up in "server" and "client", because the server side is done, but the client is not. I am not a client developer and the proposed changes require more than just license-stuff but functional testing.

I would 
1. create a new PR with server-side license changes
2. create a new branch with the current version of client-side restructuring

@bastrapp Are you fine with that?

**Comment by bastrapp** [comment]
go ahead ;-) ...
