### ISSUE TITLE
Frequently occuring error in logs adding admin

### ISSUE THREAD

**Issue by bastrapp** [ultical/ultical#53]
Every couple of days an error like this is shown in the logs

> Causing: org.apache.ibatis.exceptions.PersistenceException:
> ! ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ultical`.`TEAM_ULTICAL_USERS`, CONSTRAINT `fk_team_ultical_users_ultical_users` FOREIGN KEY (`admin`) REFERENCES `ULTICAL_USER` (`id`))
> ! ### The error may involve de.ultical.backend.data.mapper.TeamMapper.addAdmin-Inline
> ! ### The error occurred while setting parameters
> ! ### SQL: INSERT INTO TEAM_ULTICAL_USERS (team, admin) VALUES (?, ?)
> ! ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ultical`.`TEAM_ULTICAL_USERS`, CONSTRAINT `fk_team_ultical_users_ultical_users` FOREIGN KEY (`admin`) REFERENCES `ULTICAL_USER` (`id`))
> !

I cannot reproduce it

**Comment by bslbckr** [comment]
- First, glad we are having the foreign key constraints!
- Second, concerning your commit: I would strongly recommend to use a logger for this purpose. I'm not sure how much content is written to stdout.
- Third, I think we should not only have a look at the id of team and admin but also log who is trying to make this request (including current IP and user that is logged in) and what the exact payload is, that was transferred to the server.

**Comment by bslbckr** [comment]
I just created a branch 'logging-enhancement' in order to improve logging for this scenario. What is missing, is the use of the [MDC](http://logback.qos.ch/manual/mdc.html) in the logging patterns. This has to be configured in the yaml for the running server.

@bastrapp if you think the branch is "production ready" please merge it into master.

**Comment by bastrapp** [comment]
Thank you @kaffeetrinkr , could you just create the necessary configuration in the default.yaml.dist file which is under version control? I will then just copy it over to the production yaml file after the merge.

Pull request already here #55

**Comment by bslbckr** [comment]
@bastrapp I just added the required configuration.

**Comment by bastrapp** [comment]
It's live... let's see what information it brings...

**Comment by bastrapp** [comment]
first occurence

ERROR [2016-06-30 18:09:55,070] d.u.b.a.TeamResource:109.44.3.56     Error adding Admin:
Team: Frühsport 0,2 ( 54 )
User: null ( 0 )
currentUser: 66
ERROR [2016-06-30 18:09:55,089] d.u.b.a.TeamResource:109.44.3.56     exception:
! com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ultical`.`TEAM_ULTICAL_USERS`, CONSTRAINT `fk_team_ultical_users_ultical_users` FOREIGN KEY (`admin`) REFERENCES `ULTICAL_USER` (`id`))
! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
! at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
! at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[backend-0.0.1-SNAPSHOT.jar:na]
! ... 65 common frames omitted
! Causing: org.apache.ibatis.exceptions.PersistenceException: 
! ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ultical`.`TEAM_ULTICAL_USERS`, CONSTRAINT `fk_team_ultical_users_ultical_users` FOREIGN KEY (`admin`) REFERENCES `ULTICAL_USER` (`id`))
! ### The error may involve de.ultical.backend.data.mapper.TeamMapper.addAdmin-Inline
! ### The error occurred while setting parameters
! ### SQL: INSERT INTO TEAM_ULTICAL_USERS (team, admin) VALUES (?, ?)
! ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ultical`.`TEAM_ULTICAL_USERS`, CONSTRAINT `fk_team_ultical_users_ultical_users` FOREIGN KEY (`admin`) REFERENCES `ULTICAL_USER` (`id`))
! at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:56) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at com.sun.proxy.$Proxy88.addAdmin(Unknown Source) ~[na:na]
! at de.ultical.backend.data.DataStore.lambda$addAdminToTeam$0(DataStore.java:784) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at de.ultical.backend.data.DataStore.modifyTeamAdmin(DataStore.java:810) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at de.ultical.backend.data.DataStore.addAdminToTeam(DataStore.java:782) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at de.ultical.backend.api.TeamResource.update(TeamResource.java:207) ~[backend-0.0.1-SNAPSHOT.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) [backend-0.0.1-SNAPSHOT.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [backend-0.0.1-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [backend-0.0.1-SNAPSHOT.jar:na]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:132) [backend-0.0.1-SNAPSHOT.jar:na]
:

**Comment by bastrapp** [comment]
> `[06/Jul/2016:12:20:44 +0000] "PUT /teams/139 HTTP/1.1" 204 - "https://www.dfv-turniere.de/de/teams/wolpertinger--7139" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" 261`

`ERROR [2016-07-06 14:20:44,533] d.u.b.a.TeamResource:xxx.xxx.xxx.xxx  Error adding Admin:`
`Team: Wolpertinger ( 139 )`
`User: null ( 0 )`
`currentUser: 201`
`ERROR [2016-07-06 14:20:44,536] d.u.b.a.TeamResource:xxx.xxx.xxx.xxx  exception:`
`! com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails ('ultical'.'TEAM_ULTICAL_USERS', CONSTRAINT 'fk_team_ultical_users_ultical_users' FOREIGN KEY (`admin`) REFERENCES 'ULTICAL_USER' ('id'))
`

**Comment by bslbckr** [comment]
Just out of curiosity, is this error still present in the logs? Otherwise I would suggest to close this issue ;-)

**Comment by bastrapp** [comment]
Don't see this error in the logs... let's close it
