### ISSUE TITLE
Team contact email

### ISSUE THREAD

**Issue by bastrapp** [ultical/ultical#54]
As we now have a way of contacting a team without the need to expose email addresses, we could remove the "contact email" field entirely... or not?
- pro: no exposure of email address
- con: i often feel patronized if i can only use a contact form instead an email

Curious to hear your opinions... @kaffeetrinkr et al.

**Comment by bslbckr** [comment]
I share your con-concern and would therefore suggest to make the contact email field optional. Then it's up the organizer how he would like to treat his guests.

**Comment by bastrapp** [comment]
Done with 87aa4011fd5a86187bb44b13090f00b46dfd8855
