### ISSUE TITLE
Second row of contact email addresses overlaps first row

### ISSUE THREAD

**Issue by PlusMinus0** [ultical/ultical#60]
See screenshot below, might affect admins as well.

```
Version information

Version:    38.0.2220.41 - Opera is up to date
Update stream:  Stable
System: Arch Linux (x86_64; GNOME)

Browser identification

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41
```

![screenshot from 2016-07-07 15-02-26](https://cloud.githubusercontent.com/assets/11473351/16654046/3c06d3be-4454-11e6-8421-42cac56550ca.png)

**Comment by bastrapp** [comment]
Thanks!

Should be fixed now, reopen if I missed something
