### ISSUE TITLE
JDBC Pool exhausted

### ISSUE THREAD

**Issue by bastrapp** [ultical/ultical#7]
After a weekend without a restart the server couldn't access the database anymore and threw this exception:
! ### Error querying database.  Cause: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [dw-3832 - GET /season] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:100; busy:100; idle:0; lastwait:30000].

**Comment by bastrapp** [comment]
looking good so far. Server is up 24 hours with relative high request rate (many teams adding players) and still all connections in the pool ;-)

**Comment by bslbckr** [comment]
great :heavy_exclamation_mark:

**Comment by bastrapp** [comment]
After 48 hours still no sign of exhaustion... Will close this issue for now...

**Comment by bastrapp** [comment]
back again... took a longer time, but it's the same error

**Comment by bastrapp** [comment]
closing once again ;-)
