### ISSUE TITLE
Automatische Abmeldung beim Hinzufügen einen bestimmten Spielerin zum Kader

### ISSUE THREAD

**Issue by PlusMinus0** [ultical/ultical#81]
Moin,

ich habe ein reproduzierbares Problem:

Wenn ich die Spielerin Annika Behrendt zum Kader U20 Damen Juniors hinzufügen möchte werde ich abgemeldet und kann mich fortan zwar wieder anmelden, werde aber unmittelbar wieder abgemeldet (auch im anderen Browser, scheinbar funktioniert es an einem anderen Rechner, zumindest bis ich die Spielerin wieder hinzufüge).

Eine andere Spielerin konnte ich zum Kader hinzufügen.

Grüße

**Comment by bastrapp** [comment]
Die Spielerin ist als "nicht aktiv" gemeldet. Das ist ein Problem, das bei dfv-mv.de gelöst werden kann. Den Logout kann ich leider nicht reproduzieren. Will ich die Spielerin hinzufügen, passiert bei mir einfach nichts.

**Comment by PlusMinus0** [comment]
Ja, erst Mal passiert nichts, aber danach werde ich bei jedem neuen Seitenaufruf abgemeldet, auch wenn es erst einmal aussieht als würde die Anmeldung klappen.


Beispiel: (Ich habe nach dem Versuch die Spielerin hinzuzufügen die Seite aktualisiert)
![peek 2018-05-16 08-41](https://user-images.githubusercontent.com/11473351/40100639-f22985e6-58e4-11e8-9cfd-8d58a8a789dc.gif)

**Comment by bastrapp** [comment]
Ein reload der Seite loggt dich immer aus. Wir bauen keine Session auf. Ist
ein Feature für die Zukunft ;-)

PlusMinus0 <notifications@github.com> schrieb am Mi., 16. Mai 2018, 08:42:

**Comment by PlusMinus0** [comment]
Ah, okay :-D
