### ISSUE TITLE
Fehler bei der Sortierung der Spritergebnisse

### ISSUE THREAD

**Issue by PlusMinus0** [ultical/ultical#83]
Siehe Bildschirmfoto, Karlsruhe mit 11 Punkten wird vor FR&TBB und Heidees plaziert, wenn man nach Spirit sortiert.

![screenshot from 2018-12-02 20-51-29](https://user-images.githubusercontent.com/11473351/49344177-15f7ca00-f674-11e8-957a-d8e29d1a1e8e.png)

**Comment by bslbckr** [comment]
Hi @PlusMinus0 , ich habe das gerade einmal zu reproduzieren versucht:
* Seite aufrufen
* Turnier finden
* Ergebnisse sortieren

Das Ergebnis sieht bei mir so aus, wie man es auch erwartet. Vgl:
![grafik](https://user-images.githubusercontent.com/15678130/49344784-0bd9c980-f67c-11e8-8087-958ab5bb5252.png)

Auch wenn ich mich einlogge und somit, wie Du auch, Administrator des Turniers werde, bleibt das Ergebnis unverändert. 

Das ist jetzt sicherlich eine doofe Antwort, aber ich weiß tatsächlich nicht, wie ich den Bug beheben soll. Kannst Du einfach noch einmal schauen, ob der Fehler bei Dir immer noch auftritt?

**Comment by PlusMinus0** [comment]
:thinking: joa, bei mir jetzt auch. Na gut, falscher Alarm.

**Comment by bslbckr** [comment]
Wann ist Dir das denn aufgefallen, direkt nach dem Eintragen der Spiritergebnisse?

**Comment by PlusMinus0** [comment]
Genau. Hab jetzt spaßeshalber Mal das Ergebnis von Karlsruhe auf 12 geändert, dann wieder zurück und die Sortierung stimmt wieder nicht, bis ich die Seite neu geladen habe.

**Comment by bslbckr** [comment]
Schade, dass es das merkwürdige Verhalten gibt. Schön, dass es immerhin
reproduzierbar auftritt.
Schlauer bin ich noch nicht, wir schauen es uns jetzt aber Mal an.

>
